[package]
name = "rain_quantum_simulator"
version = "0.1.0"
edition = "2024"
LICENSE = "MIT"
description = "quantum computing simulator with quantum gates, registers, and state vector operations"

[dependencies]
num-traits = "0.2"
complex_rs = "0.1.0"
rain_linalg = "0.2.0"